[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn insurance_fraud_detection.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/fraud_detector/"
healthcheckTimeout = 300
restartPolicyType = "always"