[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn insurance_fraud_detection.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/fraud_detector/health/"
healthcheckTimeout = 300
restartPolicyType = "always"