# Generated by Django 4.2.7 on 2025-07-02 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fraud_detector", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="claim",
            options={"ordering": ["-fraud_score", "-date_of_loss"]},
        ),
        migrations.AddField(
            model_name="claim",
            name="attorney_involved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="claim",
            name="cause_of_injury",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="claim",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="claim",
            name="claimant_dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 7, 2, 20, 10, 6, 490280, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="claim",
            name="date_of_hire",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="date_reported",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="department",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="claim",
            name="indemnity_costs",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="job_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="claim",
            name="legal_costs",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="location_description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="claim",
            name="medical_costs",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="medical_treatment",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="claim",
            name="state",
            field=models.CharField(
                blank=True, help_text="2-letter state code", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="supervisor",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="claim",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="witness_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="claim",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="claim",
            name="claim_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="fraud_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="claim",
            name="red_flags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="claim",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                default="Low",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["risk_level"], name="fraud_detec_risk_le_aa50cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["fraud_score"], name="fraud_detec_fraud_s_b6efeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["date_of_loss"], name="fraud_detec_date_of_9b5834_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(fields=["state"], name="fraud_detec_state_0bc3e5_idx"),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["claimant_name"], name="fraud_detec_claiman_2718ba_idx"
            ),
        ),
    ]
